<?xml version ='1.0' encoding ='UTF-8' ?> 
<definitions name='Dotproject' 
  targetNamespace='http://example.org/temperature' 
  xmlns:tns=' http://example.org/temperature ' 
  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
  xmlns:xsd='http://www.w3.org/2001/XMLSchema' 
  xmlns:soapenc='http://schemas.xmlsoap.org/soap/encoding/' 
  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
  xmlns='http://schemas.xmlsoap.org/wsdl/'> 

<message name='pingResponse'> 
  <part name='symbol' type='xsd:int'/> 
</message> 

<portType name='PingPortType'> 
  <operation name='ping'> 
    <output message='tns:pingResponse'/> 
  </operation> 
</portType> 

<binding name='PingBinding' type='tns:PingPortType'> 
  <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/> 
  <operation name='ping'> 
    <soap:operation soapAction='urn:dotproject#ping'/> 
    <output> 
      <soap:body use='literal' namespace='urn:dotproject' /> 
    </output> 
  </operation> 
</binding> 

<service name='DotprojectService'> 
  <port name='PingPort' binding='PingBinding'> 
    <soap:address location='http://localhost/~magsilva/Projects/ideais/dotproject/ws/dotproject.ws.php'/> 
  </port> 
</service>
</definitions>

